select * from customer;



-- What is the total revenue generated by male vs. female customers?
select "Gender" ,sum("Sales") as total_revenue 
from customer
group by "Gender";
-- Which customers spent more than the average sales amount? Show their gender and age group.
select "Customer_Id","Gender","Aged_Group"
from customer
where "Sales">
(select avg("Sales") as average 
from customer);

---Q3. Which are the top 5 categories with the highest average sales amount?
select "Category" ,avg("Sales") as average_sales
from customer 
group by "Category"
order by average_sales desc limit 5;
--Q4. Compare the average sales amount between different payment methods.
select "Payment_Method" ,avg("Sales") as total_sales
from customer
group by "Payment_Method";

Q5. Which shopping mall generates the highest total and average revenue?
select "Shopping_Mall",max("Sales") as Maximum ,sum("Sales") as total_sales
from customer
group by "Shopping_Mall" ;

--Q6. Which 5 shopping malls have the highest total quantity of items sold?
select "Category","Shopping_Mall" ,sum("Quantity") as total_quantity
from customer
group by "Category","Shopping_Mall"
order by total_quantity desc limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
--number of purchases, and show the count of each segment.
with customer2 as
(select "Customer_Id",count("Invoice_No"),
case 
when count("Invoice_No") = 1 then 'New_customer'
when count("Invoice_No") between 2 and 5 then 'Retuning_customer'
else 'Loyal_customer'
end as Segment
from customer
group by "Customer_Id" )

select Segment ,count(*) as total_count
from customer2
group by Segment;
;

Q8. What are the top 3 most purchased categories within each shopping mall?
WITH category_sales AS (
    SELECT "Shopping_Mall", "Category",
           SUM("Quantity") AS total_quantity,
           ROW_NUMBER() OVER (
               PARTITION BY "Shopping_Mall" 
               ORDER BY SUM("Quantity") DESC
           ) AS top_most
    FROM customer
    GROUP BY "Shopping_Mall", "Category"
)
SELECT "Shopping_Mall", "Category", total_quantity, top_most
FROM category_sales
WHERE top_most <= 3;
Q9. Are customers who are repeat buyers (more than 5 purchases) contributing more to total revenue?
SELECT 
    CASE 
        WHEN COUNT("Invoice_No") > 5 THEN 'Repeat Buyer'
        ELSE 'Occasional Buyer'
    END AS buyer_type,
    COUNT("Customer_Id") AS total_customers,
    SUM("Sales") AS total_revenue,
    ROUND(AVG("Sales")::numeric, 2) AS avg_revenue
FROM customer
GROUP BY buyer_type
ORDER BY total_revenue DESC;
Q10. What is the revenue contribution of each age group?
select "Aged_Group",sum("Sales") as total_revenue
from customer
group by  "Aged_Group"
order by total_revenue desc;